### ISSUE TITLE
Switch the default for RHEL7 back to docker

### ISSUE THREAD

**Issue by myersCody** [quipucords/quipucords-installer#106]
We decided that upgrading from a 0.9.0 docker container to a 0.9.1 podman container would be rather difficult at the moment, and since we need to cut a release for downstream soon we are going to switch the default back docker. 

We will switch back to podman as the default for RHEL7 in the `0.1.3` release of the quipucords installer.

**Comment by kholdaway** [comment]
Let's hold off on this to make sure we need it.

**Comment by kholdaway** [comment]
No longer required.
