### ISSUE TITLE
Podman stop quipucords before starting postgres.

### ISSUE THREAD

**Issue by myersCody** [quipucords/quipucords-installer#120]
@myersCody commented on [Thu Sep 12 2019](https://github.com/quipucords/quipucords/issues/2008)

I think we have a timing issue regarding starting Postgres after we initially start quipucords container using Podman. 

We should stop the quipucords container so that the network is created, but gunicorn is not trying to hit our postgres container. Then instead of a restart we should just do a start.

**Comment by kholdaway** [comment]
This doesn't work.  I tried.
