### ISSUE TITLE
User Story: Improve the makefile to support common scenarios required for cutting/testing a release

### ISSUE THREAD

**Issue by myersCody** [quipucords/quipucords-installer#31]
Improve the makefile to support common scenarios required for cutting/testing a release

[Design](https://docs.google.com/document/d/14znRSJPntEybE0dO-BqUyz0Lj1oOHwn4fV3LoQk4t1E/edit?usp=sharing)
Improve `vm_helpers/Makefile`

- [x] Install-online
- [x] Install-offline
- [x] offline-install-prep

**Comment by Dostonbek1** [comment]
Closed by:
1. https://github.com/quipucords/quipucords-installer/pull/33
2. https://github.com/quipucords/quipucords-installer/pull/42
