### ISSUE TITLE
User Story: Break quipucords installer ansible roles up as designed in issue #37

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords-installer#38]
Break ansible roles up as designed in issue #37 

After a discussion with @myersCody and @Dostonbek1, we have the following
## Old Roles:
- prep (#44)
- epel (#46)
- docker (#52)
- qpc_server (#4, #48)
- qpc_cli
- validate_install

## New Roles:
- param_validation (#44)
- param_validation_offline (#44)
- install_prep (#44)
- install_epel_online (#46)
- install_docker_online (#52)
- setup_docker (#52)
- postgres_offline (#48)
- postgres (#48)
- qpc_server_common_prep (#4)
- qpc_server_online_prep (#4)
- qpc_server_online (#4)
- qpc_server_start (#4)
- qpc_cli_offline (#54)
- qpc_cli_online (#54)
- qpc_cli (#54)
- validate_install

## Newer Roles:
- validate_common 
   - move common here --> install_prep_common
- validate_offline 
    - move offline content from install_prep_common to above
- install_docker_online 
- start_docker_common
- install_postgres_offline 
- start_postgres_common 
- prep_server_online 
- prep_server_common 
- install_server_online
- start_server_common 
- install_cli_offline 
- install_cli_online 
    - install_epel_online  (theory is only CLI needs this)
- config_cli_common
- validate_server_install
- validate_cli_install
    - qpc --version |grep cli_version

**Comment by Dostonbek1** [comment]
All the sub-issues have been resolved.
